//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.FileOperations.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Windows.FileOperations.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No accessible overloaded &apos;{0}&apos; is most specific for these arguments: {1}.
        /// </summary>
        public static string AmbiguousCall_ExactMatch2 {
            get {
                return ResourceManager.GetString("AmbiguousCall_ExactMatch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No accessible overloaded &apos;{0}&apos; can be called with these arguments without a widening conversion: {1}.
        /// </summary>
        public static string AmbiguousCall_WideningConversion2 {
            get {
                return ResourceManager.GetString("AmbiguousCall_WideningConversion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No accessible overloaded &apos;{0}&apos; can be called with these arguments without a narrowing conversion: {1}.
        /// </summary>
        public static string AmbiguousCall2 {
            get {
                return ResourceManager.GetString("AmbiguousCall2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Conversion from type &apos;{0}&apos; to type &apos;{1}&apos; is ambiguous..
        /// </summary>
        public static string AmbiguousCast2 {
            get {
                return ResourceManager.GetString("AmbiguousCast2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No accessible overloaded &apos;{0}&apos; can be called without a narrowing conversion..
        /// </summary>
        public static string AmbiguousMatch_NarrowingConversion1 {
            get {
                return ResourceManager.GetString("AmbiguousMatch_NarrowingConversion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Array dimensions do not match those specified by the &apos;VBFixedArray&apos; attribute..
        /// </summary>
        public static string Argument_ArrayDimensionsDontMatch {
            get {
                return ResourceManager.GetString("Argument_ArrayDimensionsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot determine array type because it is Nothing..
        /// </summary>
        public static string Argument_ArrayNotInitialized {
            get {
                return ResourceManager.GetString("Argument_ArrayNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collection index must be in the range 1 to the size of the collection..
        /// </summary>
        public static string Argument_CollectionIndex {
            get {
                return ResourceManager.GetString("Argument_CollectionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; must be greater than or equal to -1..
        /// </summary>
        public static string Argument_GEMinusOne1 {
            get {
                return ResourceManager.GetString("Argument_GEMinusOne1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; must be greater than or equal to 1..
        /// </summary>
        public static string Argument_GEOne1 {
            get {
                return ResourceManager.GetString("Argument_GEOne1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; must be greater or equal to zero..
        /// </summary>
        public static string Argument_GEZero1 {
            get {
                return ResourceManager.GetString("Argument_GEZero1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; must be greater than zero..
        /// </summary>
        public static string Argument_GTZero1 {
            get {
                return ResourceManager.GetString("Argument_GTZero1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loop control variable of type &apos;{1}&apos; does not implement the &apos;System.IComparable&apos; interface..
        /// </summary>
        public static string Argument_IComparable2 {
            get {
                return ResourceManager.GetString("Argument_IComparable2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VbStrConv.Katakana and VbStrConv.Hiragana cannot be combined..
        /// </summary>
        public static string Argument_IllegalKataHira {
            get {
                return ResourceManager.GetString("Argument_IllegalKataHira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;{0}&apos; is a type in &apos;{1}&apos; and cannot be used as an expression..
        /// </summary>
        public static string Argument_IllegalNestedType2 {
            get {
                return ResourceManager.GetString("Argument_IllegalNestedType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VbStrConv.Wide and VbStrConv.Narrow cannot be combined..
        /// </summary>
        public static string Argument_IllegalWideNarrow {
            get {
                return ResourceManager.GetString("Argument_IllegalWideNarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; must be less than or equal to the length of argument &apos;{1}&apos;..
        /// </summary>
        public static string Argument_IndexLELength2 {
            get {
                return ResourceManager.GetString("Argument_IndexLELength2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; cannot be converted to type &apos;Date&apos;..
        /// </summary>
        public static string Argument_InvalidDateValue1 {
            get {
                return ResourceManager.GetString("Argument_InvalidDateValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Length of fixed length string cannot be zero..
        /// </summary>
        public static string Argument_InvalidFixedLengthString {
            get {
                return ResourceManager.GetString("Argument_InvalidFixedLengthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method &apos;{1}&apos; has no parameter named &apos;{0}&apos;..
        /// </summary>
        public static string Argument_InvalidNamedArg2 {
            get {
                return ResourceManager.GetString("Argument_InvalidNamedArg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Named arguments are not valid as array subscripts..
        /// </summary>
        public static string Argument_InvalidNamedArgs {
            get {
                return ResourceManager.GetString("Argument_InvalidNamedArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; is Nothing..
        /// </summary>
        public static string Argument_InvalidNullValue1 {
            get {
                return ResourceManager.GetString("Argument_InvalidNullValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument value &apos;{0}&apos; contains characters that are not valid in a path name..
        /// </summary>
        public static string Argument_InvalidPathChars1 {
            get {
                return ResourceManager.GetString("Argument_InvalidPathChars1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; is not valid for the array..
        /// </summary>
        public static string Argument_InvalidRank1 {
            get {
                return ResourceManager.GetString("Argument_InvalidRank1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arguments are not valid..
        /// </summary>
        public static string Argument_InvalidValue {
            get {
                return ResourceManager.GetString("Argument_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; is not a valid value..
        /// </summary>
        public static string Argument_InvalidValue1 {
            get {
                return ResourceManager.GetString("Argument_InvalidValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; cannot be converted to type &apos;{1}&apos;..
        /// </summary>
        public static string Argument_InvalidValueType2 {
            get {
                return ResourceManager.GetString("Argument_InvalidValueType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;Conversion&apos; is not valid..
        /// </summary>
        public static string Argument_InvalidVbStrConv {
            get {
                return ResourceManager.GetString("Argument_InvalidVbStrConv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This system does not contain support for the Japanese locale..
        /// </summary>
        public static string Argument_JPNNotSupported {
            get {
                return ResourceManager.GetString("Argument_JPNNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Locale id &apos;{0}&apos; is not supported on this system..
        /// </summary>
        public static string Argument_LCIDNotSupported1 {
            get {
                return ResourceManager.GetString("Argument_LCIDNotSupported1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Length of argument &apos;{0}&apos; must be greater than zero..
        /// </summary>
        public static string Argument_LengthGTZero1 {
            get {
                return ResourceManager.GetString("Argument_LengthGTZero1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This system does not contain support for the Locale specified..
        /// </summary>
        public static string Argument_LocalNotSupported {
            get {
                return ResourceManager.GetString("Argument_LocalNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; must be greater than 0 or equal to -1..
        /// </summary>
        public static string Argument_MinusOneOrGTZero1 {
            get {
                return ResourceManager.GetString("Argument_MinusOneOrGTZero1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type of argument &apos;{0}&apos; is &apos;{1}&apos;, which is not numeric..
        /// </summary>
        public static string Argument_NotNumericType2 {
            get {
                return ResourceManager.GetString("Argument_NotNumericType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;Path&apos; is Nothing or empty..
        /// </summary>
        public static string Argument_PathNullOrEmpty {
            get {
                return ResourceManager.GetString("Argument_PathNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; is Nothing or empty..
        /// </summary>
        public static string Argument_PathNullOrEmpty1 {
            get {
                return ResourceManager.GetString("Argument_PathNullOrEmpty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;FilePutObject&apos; of structure &apos;{0}&apos; is not valid..
        /// </summary>
        public static string Argument_PutObjectOfValueType1 {
            get {
                return ResourceManager.GetString("Argument_PutObjectOfValueType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; must be within the range 0 to 99..
        /// </summary>
        public static string Argument_Range0to99_1 {
            get {
                return ResourceManager.GetString("Argument_Range0to99_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; must be within the range 1 to 255..
        /// </summary>
        public static string Argument_Range1toFF1 {
            get {
                return ResourceManager.GetString("Argument_Range1toFF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; must be within the range of -32768 to 65535..
        /// </summary>
        public static string Argument_RangeTwoBytes1 {
            get {
                return ResourceManager.GetString("Argument_RangeTwoBytes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; cannot be a multi-dimensional array..
        /// </summary>
        public static string Argument_RankEQOne1 {
            get {
                return ResourceManager.GetString("Argument_RankEQOne1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This system does not contain support for the Simplified Chinese locale..
        /// </summary>
        public static string Argument_SCNotSupported {
            get {
                return ResourceManager.GetString("Argument_SCNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VbStrConv.SimplifiedChinese and VbStrConv.TraditionalChinese cannot be combined..
        /// </summary>
        public static string Argument_StrConvSCandTC {
            get {
                return ResourceManager.GetString("Argument_StrConvSCandTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This system does not contain support for the Traditional Chinese locale..
        /// </summary>
        public static string Argument_TCNotSupported {
            get {
                return ResourceManager.GetString("Argument_TCNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Array argument cannot have more than 2 dimensions..
        /// </summary>
        public static string Argument_UnsupportedArrayDimensions {
            get {
                return ResourceManager.GetString("Argument_UnsupportedArrayDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File I/O of a structure with field &apos;{0}&apos; of type &apos;{1}&apos; is not valid..
        /// </summary>
        public static string Argument_UnsupportedFieldType2 {
            get {
                return ResourceManager.GetString("Argument_UnsupportedFieldType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File I/O with type &apos;{0}&apos; is not valid..
        /// </summary>
        public static string Argument_UnsupportedIOType1 {
            get {
                return ResourceManager.GetString("Argument_UnsupportedIOType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VbStrConv.Wide and VbStrConv.Narrow are not applicable to the locale specified..
        /// </summary>
        public static string Argument_WideNarrowNotApplicable {
            get {
                return ResourceManager.GetString("Argument_WideNarrowNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument matching parameter &apos;{0}&apos; cannot convert from &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        public static string ArgumentMismatch3 {
            get {
                return ResourceManager.GetString("ArgumentMismatch3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument matching parameter &apos;{0}&apos; cannot convert from &apos;{1}&apos; to &apos;{2}&apos; because the conversion is ambiguous..
        /// </summary>
        public static string ArgumentMismatchAmbiguous3 {
            get {
                return ResourceManager.GetString("ArgumentMismatchAmbiguous3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ByRef parameter &apos;{0}&apos; cannot convert from &apos;{1}&apos; to &apos;{2}&apos; when assigning back to the matching argument because the conversion is ambiguous..
        /// </summary>
        public static string ArgumentMismatchAmbiguousCopyBack3 {
            get {
                return ResourceManager.GetString("ArgumentMismatchAmbiguousCopyBack3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ByRef parameter &apos;{0}&apos; cannot convert from &apos;{1}&apos; to &apos;{2}&apos; when assigning back to the matching argument..
        /// </summary>
        public static string ArgumentMismatchCopyBack3 {
            get {
                return ResourceManager.GetString("ArgumentMismatchCopyBack3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument matching parameter &apos;{0}&apos; narrows from &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        public static string ArgumentNarrowing3 {
            get {
                return ResourceManager.GetString("ArgumentNarrowing3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ByRef parameter &apos;{0}&apos; narrows from &apos;{1}&apos; to &apos;{2}&apos; when assigning back to the matching argument..
        /// </summary>
        public static string ArgumentNarrowingCopyBack3 {
            get {
                return ResourceManager.GetString("ArgumentNarrowingCopyBack3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; cannot be converted to a numeric value..
        /// </summary>
        public static string ArgumentNotNumeric1 {
            get {
                return ResourceManager.GetString("ArgumentNotNumeric1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operator &apos;{0}&apos; is not defined for {1} and {2}..
        /// </summary>
        public static string BinaryOperands3 {
            get {
                return ResourceManager.GetString("BinaryOperands3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;Before&apos; and &apos;After&apos; arguments cannot be combined..
        /// </summary>
        public static string Collection_BeforeAfterExclusive {
            get {
                return ResourceManager.GetString("Collection_BeforeAfterExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add failed. Duplicate key value supplied..
        /// </summary>
        public static string Collection_DuplicateKey {
            get {
                return ResourceManager.GetString("Collection_DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;Dir&apos; function must first be called with a &apos;PathName&apos; argument..
        /// </summary>
        public static string DIR_IllegalCall {
            get {
                return ResourceManager.GetString("DIR_IllegalCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty placeholder to adjust for 1-based array..
        /// </summary>
        public static string EmptyPlaceHolderMessage {
            get {
                return ResourceManager.GetString("EmptyPlaceHolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expression &apos;{0}&apos; is not a procedure, but occurs as the target of a procedure call..
        /// </summary>
        public static string ExpressionNotProcedure {
            get {
                return ResourceManager.GetString("ExpressionNotProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Substitution of type arguments failed..
        /// </summary>
        public static string FailedTypeArgumentBinding {
            get {
                return ResourceManager.GetString("FailedTypeArgumentBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на String length exceeds maximum length of 32767 characters for &apos;FileSystem&apos; APIs..
        /// </summary>
        public static string FileIO_StringLengthExceeded {
            get {
                return ResourceManager.GetString("FileIO_StringLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File is not opened for read access..
        /// </summary>
        public static string FileOpenedNoRead {
            get {
                return ResourceManager.GetString("FileOpenedNoRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File is not opened for write access..
        /// </summary>
        public static string FileOpenedNoWrite {
            get {
                return ResourceManager.GetString("FileOpenedNoWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drive &apos;{0}&apos; not found..
        /// </summary>
        public static string FileSystem_DriveNotFound1 {
            get {
                return ResourceManager.GetString("FileSystem_DriveNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File &apos;{0}&apos; cannot be deleted because it is open..
        /// </summary>
        public static string FileSystem_FileAlreadyOpen1 {
            get {
                return ResourceManager.GetString("FileSystem_FileAlreadyOpen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File &apos;{0}&apos; not found..
        /// </summary>
        public static string FileSystem_FileNotFound1 {
            get {
                return ResourceManager.GetString("FileSystem_FileNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;Access&apos; is not valid. Valid values for Append mode are &apos;OpenAccess.Write&apos; and &apos;OpenAccess.Default&apos;..
        /// </summary>
        public static string FileSystem_IllegalAppendAccess {
            get {
                return ResourceManager.GetString("FileSystem_IllegalAppendAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;Access&apos; is not valid. Valid values for Input mode are &apos;OpenAccess.Read&apos; and &apos;OpenAccess.Default&apos;..
        /// </summary>
        public static string FileSystem_IllegalInputAccess {
            get {
                return ResourceManager.GetString("FileSystem_IllegalInputAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;Access&apos; is not valid. Valid values for Output mode are &apos;OpenAccess.Write&apos; and &apos;OpenAccess.Default&apos;..
        /// </summary>
        public static string FileSystem_IllegalOutputAccess {
            get {
                return ResourceManager.GetString("FileSystem_IllegalOutputAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path &apos;{0}&apos; not found..
        /// </summary>
        public static string FileSystem_PathNotFound1 {
            get {
                return ResourceManager.GetString("FileSystem_PathNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; must be greater than or equal to zero..
        /// </summary>
        public static string Financial_ArgGEZero1 {
            get {
                return ResourceManager.GetString("Financial_ArgGEZero1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; must be greater than zero..
        /// </summary>
        public static string Financial_ArgGTZero1 {
            get {
                return ResourceManager.GetString("Financial_ArgGTZero1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Division by zero..
        /// </summary>
        public static string Financial_CalcDivByZero {
            get {
                return ResourceManager.GetString("Financial_CalcDivByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot calculate number of periods using the arguments provided..
        /// </summary>
        public static string Financial_CannotCalculateNPer {
            get {
                return ResourceManager.GetString("Financial_CannotCalculateNPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot calculate rate using the arguments provided..
        /// </summary>
        public static string Financial_CannotCalculateRate {
            get {
                return ResourceManager.GetString("Financial_CannotCalculateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;Life&apos; cannot be zero..
        /// </summary>
        public static string Financial_LifeNEZero {
            get {
                return ResourceManager.GetString("Financial_LifeNEZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;Period&apos; must be less than or equal to argument &apos;Life&apos;..
        /// </summary>
        public static string Financial_PeriodLELife {
            get {
                return ResourceManager.GetString("Financial_PeriodLELife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot convert start value of type &apos;{0}&apos; and step value of type &apos;{1}&apos; to a common numeric type..
        /// </summary>
        public static string ForLoop_CommonType2 {
            get {
                return ResourceManager.GetString("ForLoop_CommonType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot convert start value of type &apos;{0}&apos;, limit value of type &apos;{1}&apos;, and step value of type &apos;{2}&apos; to a common numeric type..
        /// </summary>
        public static string ForLoop_CommonType3 {
            get {
                return ResourceManager.GetString("ForLoop_CommonType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot convert argument &apos;{0}&apos; of type &apos;{1}&apos; to type &apos;{2}&apos;..
        /// </summary>
        public static string ForLoop_ConvertToType3 {
            get {
                return ResourceManager.GetString("ForLoop_ConvertToType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type &apos;{0}&apos; must define an operator &apos;{1}&apos;, with parameters of type &apos;{0}&apos;, to be used in a &apos;For&apos; statement..
        /// </summary>
        public static string ForLoop_OperatorRequired2 {
            get {
                return ResourceManager.GetString("ForLoop_OperatorRequired2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return and parameter types of &apos;{0}&apos; must be of type &apos;{1}&apos; to be used in a &apos;For&apos; statement..
        /// </summary>
        public static string ForLoop_UnacceptableOperator2 {
            get {
                return ResourceManager.GetString("ForLoop_UnacceptableOperator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter types of &apos;{0}&apos; must be of type &apos;{1}&apos; to be used in a &apos;For&apos; statement..
        /// </summary>
        public static string ForLoop_UnacceptableRelOperator2 {
            get {
                return ResourceManager.GetString("ForLoop_UnacceptableRelOperator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; cannot be an empty string or Nothing..
        /// </summary>
        public static string General_ArgumentEmptyOrNothing_Name {
            get {
                return ResourceManager.GetString("General_ArgumentEmptyOrNothing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument cannot be Nothing..
        /// </summary>
        public static string General_ArgumentNullException {
            get {
                return ResourceManager.GetString("General_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This array is fixed or temporarily locked..
        /// </summary>
        public static string ID10 {
            get {
                return ResourceManager.GetString("ID10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class &apos;{0}&apos; does not implement the System.Collections.ICollection interface..
        /// </summary>
        public static string ID100 {
            get {
                return ResourceManager.GetString("ID100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Division by zero..
        /// </summary>
        public static string ID11 {
            get {
                return ResourceManager.GetString("ID11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type mismatch..
        /// </summary>
        public static string ID13 {
            get {
                return ResourceManager.GetString("ID13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Out of string space..
        /// </summary>
        public static string ID14 {
            get {
                return ResourceManager.GetString("ID14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expression too complex..
        /// </summary>
        public static string ID16 {
            get {
                return ResourceManager.GetString("ID16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t perform requested operation..
        /// </summary>
        public static string ID17 {
            get {
                return ResourceManager.GetString("ID17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User interrupt occurred..
        /// </summary>
        public static string ID18 {
            get {
                return ResourceManager.GetString("ID18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resume without error..
        /// </summary>
        public static string ID20 {
            get {
                return ResourceManager.GetString("ID20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Out of stack space..
        /// </summary>
        public static string ID28 {
            get {
                return ResourceManager.GetString("ID28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This Error number is obsolete and no longer used..
        /// </summary>
        public static string ID3 {
            get {
                return ResourceManager.GetString("ID3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File format is not valid..
        /// </summary>
        public static string ID321 {
            get {
                return ResourceManager.GetString("ID321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot create necessary temporary file..
        /// </summary>
        public static string ID322 {
            get {
                return ResourceManager.GetString("ID322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Format in resource file is not valid..
        /// </summary>
        public static string ID325 {
            get {
                return ResourceManager.GetString("ID325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feature not yet implemented..
        /// </summary>
        public static string ID32768 {
            get {
                return ResourceManager.GetString("ID32768", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sub or Function not defined..
        /// </summary>
        public static string ID35 {
            get {
                return ResourceManager.GetString("ID35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property value is not valid..
        /// </summary>
        public static string ID380 {
            get {
                return ResourceManager.GetString("ID380", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property array index is not valid..
        /// </summary>
        public static string ID381 {
            get {
                return ResourceManager.GetString("ID381", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set not supported at runtime..
        /// </summary>
        public static string ID382 {
            get {
                return ResourceManager.GetString("ID382", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set not supported (read-only property)..
        /// </summary>
        public static string ID383 {
            get {
                return ResourceManager.GetString("ID383", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Need property array index..
        /// </summary>
        public static string ID385 {
            get {
                return ResourceManager.GetString("ID385", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set not permitted..
        /// </summary>
        public static string ID387 {
            get {
                return ResourceManager.GetString("ID387", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get not supported at runtime..
        /// </summary>
        public static string ID393 {
            get {
                return ResourceManager.GetString("ID393", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get not supported (write-only property)..
        /// </summary>
        public static string ID394 {
            get {
                return ResourceManager.GetString("ID394", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property not found..
        /// </summary>
        public static string ID422 {
            get {
                return ResourceManager.GetString("ID422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property or method not found..
        /// </summary>
        public static string ID423 {
            get {
                return ResourceManager.GetString("ID423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object required..
        /// </summary>
        public static string ID424 {
            get {
                return ResourceManager.GetString("ID424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot create ActiveX component..
        /// </summary>
        public static string ID429 {
            get {
                return ResourceManager.GetString("ID429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class does not support Automation or does not support expected interface..
        /// </summary>
        public static string ID430 {
            get {
                return ResourceManager.GetString("ID430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File name or class name not found during Automation operation..
        /// </summary>
        public static string ID432 {
            get {
                return ResourceManager.GetString("ID432", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object does not support this property or method..
        /// </summary>
        public static string ID438 {
            get {
                return ResourceManager.GetString("ID438", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automation error..
        /// </summary>
        public static string ID440 {
            get {
                return ResourceManager.GetString("ID440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection to type library or object library for remote process has been lost. Press OK for dialog to remove reference..
        /// </summary>
        public static string ID442 {
            get {
                return ResourceManager.GetString("ID442", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automation object does not have a default value..
        /// </summary>
        public static string ID443 {
            get {
                return ResourceManager.GetString("ID443", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object does not support this action..
        /// </summary>
        public static string ID445 {
            get {
                return ResourceManager.GetString("ID445", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object does not support named arguments..
        /// </summary>
        public static string ID446 {
            get {
                return ResourceManager.GetString("ID446", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object does not support current locale setting..
        /// </summary>
        public static string ID447 {
            get {
                return ResourceManager.GetString("ID447", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Named argument not found..
        /// </summary>
        public static string ID448 {
            get {
                return ResourceManager.GetString("ID448", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument not optional..
        /// </summary>
        public static string ID449 {
            get {
                return ResourceManager.GetString("ID449", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong number of arguments or property assignment was not valid..
        /// </summary>
        public static string ID450 {
            get {
                return ResourceManager.GetString("ID450", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property let procedure not defined and property get procedure did not return an object..
        /// </summary>
        public static string ID451 {
            get {
                return ResourceManager.GetString("ID451", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ordinal is not valid..
        /// </summary>
        public static string ID452 {
            get {
                return ResourceManager.GetString("ID452", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specified DLL function not found..
        /// </summary>
        public static string ID453 {
            get {
                return ResourceManager.GetString("ID453", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code resource not found..
        /// </summary>
        public static string ID454 {
            get {
                return ResourceManager.GetString("ID454", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code resource lock error..
        /// </summary>
        public static string ID455 {
            get {
                return ResourceManager.GetString("ID455", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This key is already associated with an element of this collection..
        /// </summary>
        public static string ID457 {
            get {
                return ResourceManager.GetString("ID457", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Variable uses an Automation type not supported in Visual Basic..
        /// </summary>
        public static string ID458 {
            get {
                return ResourceManager.GetString("ID458", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object or class does not support the set of events..
        /// </summary>
        public static string ID459 {
            get {
                return ResourceManager.GetString("ID459", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clipboard format is not valid..
        /// </summary>
        public static string ID460 {
            get {
                return ResourceManager.GetString("ID460", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method or data member not found..
        /// </summary>
        public static string ID461 {
            get {
                return ResourceManager.GetString("ID461", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The remote server machine does not exist or is unavailable..
        /// </summary>
        public static string ID462 {
            get {
                return ResourceManager.GetString("ID462", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class not registered on local machine..
        /// </summary>
        public static string ID463 {
            get {
                return ResourceManager.GetString("ID463", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Too many DLL application clients..
        /// </summary>
        public static string ID47 {
            get {
                return ResourceManager.GetString("ID47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error in loading DLL..
        /// </summary>
        public static string ID48 {
            get {
                return ResourceManager.GetString("ID48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Picture is not valid..
        /// </summary>
        public static string ID481 {
            get {
                return ResourceManager.GetString("ID481", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Printer error..
        /// </summary>
        public static string ID482 {
            get {
                return ResourceManager.GetString("ID482", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad DLL calling convention..
        /// </summary>
        public static string ID49 {
            get {
                return ResourceManager.GetString("ID49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Procedure call or argument is not valid..
        /// </summary>
        public static string ID5 {
            get {
                return ResourceManager.GetString("ID5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internal error..
        /// </summary>
        public static string ID51 {
            get {
                return ResourceManager.GetString("ID51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad file name or number..
        /// </summary>
        public static string ID52 {
            get {
                return ResourceManager.GetString("ID52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File not found..
        /// </summary>
        public static string ID53 {
            get {
                return ResourceManager.GetString("ID53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad file mode..
        /// </summary>
        public static string ID54 {
            get {
                return ResourceManager.GetString("ID54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File already open..
        /// </summary>
        public static string ID55 {
            get {
                return ResourceManager.GetString("ID55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device I/O error..
        /// </summary>
        public static string ID57 {
            get {
                return ResourceManager.GetString("ID57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File already exists..
        /// </summary>
        public static string ID58 {
            get {
                return ResourceManager.GetString("ID58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad record length..
        /// </summary>
        public static string ID59 {
            get {
                return ResourceManager.GetString("ID59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overflow..
        /// </summary>
        public static string ID6 {
            get {
                return ResourceManager.GetString("ID6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disk full..
        /// </summary>
        public static string ID61 {
            get {
                return ResourceManager.GetString("ID61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input past end of file..
        /// </summary>
        public static string ID62 {
            get {
                return ResourceManager.GetString("ID62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad record number..
        /// </summary>
        public static string ID63 {
            get {
                return ResourceManager.GetString("ID63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Too many files..
        /// </summary>
        public static string ID67 {
            get {
                return ResourceManager.GetString("ID67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device unavailable..
        /// </summary>
        public static string ID68 {
            get {
                return ResourceManager.GetString("ID68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Out of memory..
        /// </summary>
        public static string ID7 {
            get {
                return ResourceManager.GetString("ID7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permission denied..
        /// </summary>
        public static string ID70 {
            get {
                return ResourceManager.GetString("ID70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disk not ready..
        /// </summary>
        public static string ID71 {
            get {
                return ResourceManager.GetString("ID71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot save file to TEMP..
        /// </summary>
        public static string ID735 {
            get {
                return ResourceManager.GetString("ID735", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot rename with different drive..
        /// </summary>
        public static string ID74 {
            get {
                return ResourceManager.GetString("ID74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search text not found..
        /// </summary>
        public static string ID744 {
            get {
                return ResourceManager.GetString("ID744", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replacements too long..
        /// </summary>
        public static string ID746 {
            get {
                return ResourceManager.GetString("ID746", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path/File access error..
        /// </summary>
        public static string ID75 {
            get {
                return ResourceManager.GetString("ID75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path not found..
        /// </summary>
        public static string ID76 {
            get {
                return ResourceManager.GetString("ID76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subscript out of range..
        /// </summary>
        public static string ID9 {
            get {
                return ResourceManager.GetString("ID9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object variable or With block variable not set..
        /// </summary>
        public static string ID91 {
            get {
                return ResourceManager.GetString("ID91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For loop not initialized..
        /// </summary>
        public static string ID92 {
            get {
                return ResourceManager.GetString("ID92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pattern string is not valid..
        /// </summary>
        public static string ID93 {
            get {
                return ResourceManager.GetString("ID93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This Error number is obsolete and no longer used..
        /// </summary>
        public static string ID94 {
            get {
                return ResourceManager.GetString("ID94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application-defined or object-defined error..
        /// </summary>
        public static string ID95 {
            get {
                return ResourceManager.GetString("ID95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to sink events of object because the object is already firing events to the maximum number of event receivers that it supports..
        /// </summary>
        public static string ID96 {
            get {
                return ResourceManager.GetString("ID96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot call friend function on object that is not an instance of defining class..
        /// </summary>
        public static string ID97 {
            get {
                return ResourceManager.GetString("ID97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A property or method call cannot include a reference to a private object, either as an argument or as a return value..
        /// </summary>
        public static string ID98 {
            get {
                return ResourceManager.GetString("ID98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop statement encountered..
        /// </summary>
        public static string ID999 {
            get {
                return ResourceManager.GetString("ID999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registry key &apos;{0}&apos; could not be created..
        /// </summary>
        public static string Interaction_ResKeyNotCreated1 {
            get {
                return ResourceManager.GetString("Interaction_ResKeyNotCreated1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invocation of &apos;{0}&apos; on type &apos;{1}&apos; returned Nothing..
        /// </summary>
        public static string IntermediateLateBoundNothingResult1 {
            get {
                return ResourceManager.GetString("IntermediateLateBoundNothingResult1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internal error in the Microsoft Visual Basic runtime..
        /// </summary>
        public static string InternalError_VisualBasicRuntime {
            get {
                return ResourceManager.GetString("InternalError_VisualBasicRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arguments to &apos;VBFixedArrayAttribute&apos; are not valid..
        /// </summary>
        public static string Invalid_VBFixedArray {
            get {
                return ResourceManager.GetString("Invalid_VBFixedArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arguments to &apos;VBFixedStringAttribute&apos; are not valid..
        /// </summary>
        public static string Invalid_VBFixedString {
            get {
                return ResourceManager.GetString("Invalid_VBFixedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Conversion from string &quot;{0}&quot; to type &apos;{1}&apos; is not valid..
        /// </summary>
        public static string InvalidCast_FromStringTo {
            get {
                return ResourceManager.GetString("InvalidCast_FromStringTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Conversion from type &apos;{0}&apos; to type &apos;{1}&apos; is not valid..
        /// </summary>
        public static string InvalidCast_FromTo {
            get {
                return ResourceManager.GetString("InvalidCast_FromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument {1} to method &apos;{0}&apos; has type &apos;{2}&apos; and cannot be converted to &apos;{3}&apos;..
        /// </summary>
        public static string InvalidCast_FromToArg4 {
            get {
                return ResourceManager.GetString("InvalidCast_FromToArg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;{0}&apos; must be a name, and not a relative or absolute path: &apos;{1}&apos;..
        /// </summary>
        public static string IO_ArgumentIsPath_Name_Path {
            get {
                return ResourceManager.GetString("IO_ArgumentIsPath_Name_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not complete operation on some files and directories. See the Data property of the exception for more details..
        /// </summary>
        public static string IO_CopyMoveRecursive {
            get {
                return ResourceManager.GetString("IO_CopyMoveRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not complete operation since target directory is under source directory..
        /// </summary>
        public static string IO_CyclicOperation {
            get {
                return ResourceManager.GetString("IO_CyclicOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The given path is a Win32 device path. Don&apos;t use paths starting with &apos;\\.\&apos;..
        /// </summary>
        public static string IO_DevicePath {
            get {
                return ResourceManager.GetString("IO_DevicePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not complete operation since a directory already exists in this path &apos;{0}&apos;..
        /// </summary>
        public static string IO_DirectoryExists_Path {
            get {
                return ResourceManager.GetString("IO_DirectoryExists_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not complete operation since directory is a root directory: &apos;{0}&apos;..
        /// </summary>
        public static string IO_DirectoryIsRoot_Path {
            get {
                return ResourceManager.GetString("IO_DirectoryIsRoot_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not find directory &apos;{0}&apos;..
        /// </summary>
        public static string IO_DirectoryNotFound_Path {
            get {
                return ResourceManager.GetString("IO_DirectoryNotFound_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not complete operation since a file already exists in this path &apos;{0}&apos;..
        /// </summary>
        public static string IO_FileExists_Path {
            get {
                return ResourceManager.GetString("IO_FileExists_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not find file &apos;{0}&apos;..
        /// </summary>
        public static string IO_FileNotFound_Path {
            get {
                return ResourceManager.GetString("IO_FileNotFound_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The given file path ends with a directory separator character..
        /// </summary>
        public static string IO_FilePathException {
            get {
                return ResourceManager.GetString("IO_FilePathException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One of the wildcards is Nothing or empty string..
        /// </summary>
        public static string IO_GetFiles_NullPattern {
            get {
                return ResourceManager.GetString("IO_GetFiles_NullPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not get parent path since the given path is a root directory: &apos;{0}&apos;..
        /// </summary>
        public static string IO_GetParentPathIsRoot_Path {
            get {
                return ResourceManager.GetString("IO_GetParentPathIsRoot_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not complete operation since source directory and target directory are the same..
        /// </summary>
        public static string IO_SourceEqualsTargetDirectory {
            get {
                return ResourceManager.GetString("IO_SourceEqualsTargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All users&apos; application data.
        /// </summary>
        public static string IO_SpecialDirectory_AllUserAppData {
            get {
                return ResourceManager.GetString("IO_SpecialDirectory_AllUserAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Desktop.
        /// </summary>
        public static string IO_SpecialDirectory_Desktop {
            get {
                return ResourceManager.GetString("IO_SpecialDirectory_Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Documents.
        /// </summary>
        public static string IO_SpecialDirectory_MyDocuments {
            get {
                return ResourceManager.GetString("IO_SpecialDirectory_MyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Music.
        /// </summary>
        public static string IO_SpecialDirectory_MyMusic {
            get {
                return ResourceManager.GetString("IO_SpecialDirectory_MyMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Pictures.
        /// </summary>
        public static string IO_SpecialDirectory_MyPictures {
            get {
                return ResourceManager.GetString("IO_SpecialDirectory_MyPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program Files.
        /// </summary>
        public static string IO_SpecialDirectory_ProgramFiles {
            get {
                return ResourceManager.GetString("IO_SpecialDirectory_ProgramFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Programs.
        /// </summary>
        public static string IO_SpecialDirectory_Programs {
            get {
                return ResourceManager.GetString("IO_SpecialDirectory_Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temporary directory.
        /// </summary>
        public static string IO_SpecialDirectory_Temp {
            get {
                return ResourceManager.GetString("IO_SpecialDirectory_Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current user&apos;s application data.
        /// </summary>
        public static string IO_SpecialDirectory_UserAppData {
            get {
                return ResourceManager.GetString("IO_SpecialDirectory_UserAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not find special directory &apos;{0}&apos;..
        /// </summary>
        public static string IO_SpecialDirectoryNotExist {
            get {
                return ResourceManager.GetString("IO_SpecialDirectoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No files found matching &apos;{0}&apos;..
        /// </summary>
        public static string KILL_NoFilesFound1 {
            get {
                return ResourceManager.GetString("KILL_NoFilesFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Managed classes derived from a COM class cannot be called late bound..
        /// </summary>
        public static string LateboundCallToInheritedComClass {
            get {
                return ResourceManager.GetString("LateboundCallToInheritedComClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;StrConv.LinguisticCasing&apos; requires &apos;StrConv.Lowercase&apos; or &apos;StrConv.Uppercase&apos;..
        /// </summary>
        public static string LinguisticRequirements {
            get {
                return ResourceManager.GetString("LinguisticRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method invocation failed because &apos;{0}&apos; cannot be called with these arguments:{1}.
        /// </summary>
        public static string MatchArgumentFailure2 {
            get {
                return ResourceManager.GetString("MatchArgumentFailure2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error number must be within the range 0 to 65535..
        /// </summary>
        public static string MaxErrNumber {
            get {
                return ResourceManager.GetString("MaxErrNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method &apos;{0}&apos; cannot be the target of an assignment..
        /// </summary>
        public static string MethodAssignment1 {
            get {
                return ResourceManager.GetString("MethodAssignment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method requires System.Windows.Forms..
        /// </summary>
        public static string MethodRequiresSystemWindowsForms {
            get {
                return ResourceManager.GetString("MethodRequiresSystemWindowsForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Public Let &apos;{0}&apos; on type &apos;{1}&apos; not found.  Use &apos;CallByName&apos; function with &apos;CallType.Set&apos;..
        /// </summary>
        public static string MissingMember_MemberLetNotFoundOnType2 {
            get {
                return ResourceManager.GetString("MissingMember_MemberLetNotFoundOnType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Public member &apos;{0}&apos; on type &apos;{1}&apos; not found..
        /// </summary>
        public static string MissingMember_MemberNotFoundOnType2 {
            get {
                return ResourceManager.GetString("MissingMember_MemberNotFoundOnType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Public Set &apos;{0}&apos; on type &apos;{1}&apos; not found.  Use &apos;CallByName&apos; function with &apos;CallType.Let&apos;..
        /// </summary>
        public static string MissingMember_MemberSetNotFoundOnType2 {
            get {
                return ResourceManager.GetString("MissingMember_MemberSetNotFoundOnType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No default member found for type &apos;{0}&apos;..
        /// </summary>
        public static string MissingMember_NoDefaultMemberFound1 {
            get {
                return ResourceManager.GetString("MissingMember_NoDefaultMemberFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &apos;{0}&apos; of type &apos;{1}&apos; is &apos;ReadOnly&apos;..
        /// </summary>
        public static string MissingMember_ReadOnlyField2 {
            get {
                return ResourceManager.GetString("MissingMember_ReadOnlyField2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Named argument &apos;{0}&apos; specified multiple times..
        /// </summary>
        public static string NamedArgumentAlreadyUsed1 {
            get {
                return ResourceManager.GetString("NamedArgumentAlreadyUsed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Named arguments cannot match ParamArray parameters..
        /// </summary>
        public static string NamedArgumentOnParamArray {
            get {
                return ResourceManager.GetString("NamedArgumentOnParamArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter &apos;{0}&apos; of &apos;{1}&apos; already has a matching argument..
        /// </summary>
        public static string NamedArgUsedTwice2 {
            get {
                return ResourceManager.GetString("NamedArgUsedTwice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Named argument &apos;{0}&apos; cannot match a ParamArray parameter..
        /// </summary>
        public static string NamedParamArrayArgument1 {
            get {
                return ResourceManager.GetString("NamedParamArrayArgument1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Named argument &apos;{0}&apos; matches no parameter of &apos;{1}&apos;..
        /// </summary>
        public static string NamedParamNotFound2 {
            get {
                return ResourceManager.GetString("NamedParamNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overload resolution failed because no accessible &apos;{0}&apos; accepts this number of arguments..
        /// </summary>
        public static string NoArgumentCountOverloadCandidates1 {
            get {
                return ResourceManager.GetString("NoArgumentCountOverloadCandidates1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overload resolution failed because no Public &apos;{0}&apos; can be called with these arguments:{1}.
        /// </summary>
        public static string NoCallableOverloadCandidates2 {
            get {
                return ResourceManager.GetString("NoCallableOverloadCandidates2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property &apos;{0}&apos; is WriteOnly..
        /// </summary>
        public static string NoGetProperty1 {
            get {
                return ResourceManager.GetString("NoGetProperty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method &apos;{0}&apos; cannot be called with {1} argument(s)..
        /// </summary>
        public static string NoMethodTakingXArguments2 {
            get {
                return ResourceManager.GetString("NoMethodTakingXArguments2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overload resolution failed because no Public &apos;{0}&apos; is most specific for these arguments:{1}.
        /// </summary>
        public static string NoMostSpecificOverload2 {
            get {
                return ResourceManager.GetString("NoMostSpecificOverload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overload resolution failed because no Public &apos;{0}&apos; can be called without a narrowing conversion:{1}.
        /// </summary>
        public static string NoNonNarrowingOverloadCandidates2 {
            get {
                return ResourceManager.GetString("NoNonNarrowingOverloadCandidates2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property &apos;{0}&apos; is ReadOnly..
        /// </summary>
        public static string NoSetProperty1 {
            get {
                return ResourceManager.GetString("NoSetProperty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UI not available for copy or move.
        /// </summary>
        public static string NoShellCopyOrMove {
            get {
                return ResourceManager.GetString("NoShellCopyOrMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not most specific..
        /// </summary>
        public static string NotMostSpecificOverload {
            get {
                return ResourceManager.GetString("NotMostSpecificOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overload resolution failed because no accessible &apos;{0}&apos; accepts this number of type arguments..
        /// </summary>
        public static string NoTypeArgumentCountOverloadCandidates1 {
            get {
                return ResourceManager.GetString("NoTypeArgumentCountOverloadCandidates1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на type &apos;{0}&apos;.
        /// </summary>
        public static string NoValidOperator_NonStringType1 {
            get {
                return ResourceManager.GetString("NoValidOperator_NonStringType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operator is not defined for type &apos;{0}&apos;..
        /// </summary>
        public static string NoValidOperator_OneOperand {
            get {
                return ResourceManager.GetString("NoValidOperator_OneOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на string &quot;{0}&quot;.
        /// </summary>
        public static string NoValidOperator_StringType1 {
            get {
                return ResourceManager.GetString("NoValidOperator_StringType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operator is not defined for {0} and {1}..
        /// </summary>
        public static string NoValidOperator_TwoOperands {
            get {
                return ResourceManager.GetString("NoValidOperator_TwoOperands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overload resolution failed because no &apos;{0}&apos; is Public..
        /// </summary>
        public static string NoViableOverloadCandidates1 {
            get {
                return ResourceManager.GetString("NoViableOverloadCandidates1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reference to non-shared member &apos;{0}&apos; requires an object reference..
        /// </summary>
        public static string NullReference_InstanceReqToAccessMember1 {
            get {
                return ResourceManager.GetString("NullReference_InstanceReqToAccessMember1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument not specified for parameter &apos;{0}&apos;..
        /// </summary>
        public static string OmittedArgument1 {
            get {
                return ResourceManager.GetString("OmittedArgument1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Omitted argument cannot match a ParamArray parameter..
        /// </summary>
        public static string OmittedParamArrayArgument {
            get {
                return ResourceManager.GetString("OmittedParamArrayArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On;On;Off.
        /// </summary>
        public static string OnOffFormatStyle {
            get {
                return ResourceManager.GetString("OnOffFormatStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;Per&apos; is not valid..
        /// </summary>
        public static string PPMT_PerGT0AndLTNPer {
            get {
                return ResourceManager.GetString("PPMT_PerGT0AndLTNPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Call to set property &apos;{0}&apos; requires at least one argument..
        /// </summary>
        public static string PropertySetMissingArgument1 {
            get {
                return ResourceManager.GetString("PropertySetMissingArgument1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &apos;NPer&apos; must be greater than zero..
        /// </summary>
        public static string Rate_NPerMustBeGTZero {
            get {
                return ResourceManager.GetString("Rate_NPerMustBeGTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Late-bound assignment to a field of value type &apos;{0}&apos; is not valid when &apos;{1}&apos; is the result of a late-bound expression..
        /// </summary>
        public static string RValueBaseForValueType {
            get {
                return ResourceManager.GetString("RValueBaseForValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Late bound calls to file system methods in the Visual Basic runtime are not permitted..
        /// </summary>
        public static string Security_LateBoundCallsNotPermitted {
            get {
                return ResourceManager.GetString("Security_LateBoundCallsNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insufficient security permissions to set the system date..
        /// </summary>
        public static string SetLocalDateFailure {
            get {
                return ResourceManager.GetString("SetLocalDateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insufficient security permissions to set the system time..
        /// </summary>
        public static string SetLocalTimeFailure {
            get {
                return ResourceManager.GetString("SetLocalTimeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на False.
        /// </summary>
        public static string StringFalse {
            get {
                return ResourceManager.GetString("StringFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на True.
        /// </summary>
        public static string StringTrue {
            get {
                return ResourceManager.GetString("StringTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;SyncLock&apos; operand cannot be of type &apos;{0}&apos; because &apos;{0}&apos; is not a reference type..
        /// </summary>
        public static string SyncLockRequiresReferenceType1 {
            get {
                return ResourceManager.GetString("SyncLockRequiresReferenceType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextFieldParser is unable to complete the read operation because maximum buffer size has been exceeded..
        /// </summary>
        public static string TextFieldParser_BufferExceededMaxSize {
            get {
                return ResourceManager.GetString("TextFieldParser_BufferExceededMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A delimiter cannot be Nothing or an empty String..
        /// </summary>
        public static string TextFieldParser_DelimiterNothing {
            get {
                return ResourceManager.GetString("TextFieldParser_DelimiterNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to read delimited fields because Delimiters is Nothing or empty..
        /// </summary>
        public static string TextFieldParser_DelimitersNothing {
            get {
                return ResourceManager.GetString("TextFieldParser_DelimitersNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextFieldParser does not support delimiters that contain end-of-line characters..
        /// </summary>
        public static string TextFieldParser_EndCharsInDelimiter {
            get {
                return ResourceManager.GetString("TextFieldParser_EndCharsInDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All field widths, except the last element, must be greater than zero. A field width less than or equal to zero in the last element indicates the last field is of variable length..
        /// </summary>
        public static string TextFieldParser_FieldWidthsMustPositive {
            get {
                return ResourceManager.GetString("TextFieldParser_FieldWidthsMustPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to read fixed width fields because FieldWidths is Nothing or empty..
        /// </summary>
        public static string TextFieldParser_FieldWidthsNothing {
            get {
                return ResourceManager.GetString("TextFieldParser_FieldWidthsNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to read delimited fields because a double quote is not a legal delimiter when HasFieldsEnclosedInQuotes is set to True..
        /// </summary>
        public static string TextFieldParser_IllegalDelimiter {
            get {
                return ResourceManager.GetString("TextFieldParser_IllegalDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A double quote is not a valid comment token for delimited fields where HasFieldsEnclosedInQuotes is set to True..
        /// </summary>
        public static string TextFieldParser_InvalidComment {
            get {
                return ResourceManager.GetString("TextFieldParser_InvalidComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Line {0} cannot be parsed using the current Delimiters..
        /// </summary>
        public static string TextFieldParser_MalFormedDelimitedLine {
            get {
                return ResourceManager.GetString("TextFieldParser_MalFormedDelimitedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Line Number:{0}.
        /// </summary>
        public static string TextFieldParser_MalformedExtraData {
            get {
                return ResourceManager.GetString("TextFieldParser_MalformedExtraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Line {0} cannot be parsed using the current FieldWidths..
        /// </summary>
        public static string TextFieldParser_MalFormedFixedWidthLine {
            get {
                return ResourceManager.GetString("TextFieldParser_MalFormedFixedWidthLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Line {0} cannot be read because it exceeds the maximum line size..
        /// </summary>
        public static string TextFieldParser_MaxLineSizeExceeded {
            get {
                return ResourceManager.GetString("TextFieldParser_MaxLineSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NumberOfChars must be greater than zero..
        /// </summary>
        public static string TextFieldParser_NumberOfCharsMustBePositive {
            get {
                return ResourceManager.GetString("TextFieldParser_NumberOfCharsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The stream passed to TextFieldParser cannot be read..
        /// </summary>
        public static string TextFieldParser_StreamNotReadable {
            get {
                return ResourceManager.GetString("TextFieldParser_StreamNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextFieldParser does not support comment tokens that contain white space..
        /// </summary>
        public static string TextFieldParser_WhitespaceInToken {
            get {
                return ResourceManager.GetString("TextFieldParser_WhitespaceInToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на True;True;False.
        /// </summary>
        public static string TrueFalseFormatStyle {
            get {
                return ResourceManager.GetString("TrueFalseFormatStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type argument inference fails for argument matching parameter &apos;{0}&apos;..
        /// </summary>
        public static string TypeInferenceFails1 {
            get {
                return ResourceManager.GetString("TypeInferenceFails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operator &apos;{0}&apos; is not defined for type &apos;{1}&apos;..
        /// </summary>
        public static string UnaryOperand2 {
            get {
                return ResourceManager.GetString("UnaryOperand2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type parameter &apos;{0}&apos; cannot be determined..
        /// </summary>
        public static string UnboundTypeParam1 {
            get {
                return ResourceManager.GetString("UnboundTypeParam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use &apos;FilePutObject&apos; instead of &apos;FilePut&apos; when using argument of type &apos;Object&apos;..
        /// </summary>
        public static string UseFilePutObject {
            get {
                return ResourceManager.GetString("UseFilePutObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes;Yes;No.
        /// </summary>
        public static string YesNoFormatStyle {
            get {
                return ResourceManager.GetString("YesNoFormatStyle", resourceCulture);
            }
        }
    }
}
