//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFiler.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XFiler.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string ExlporerTab_ContextMenu_OpenInNativeExplorer {
            get {
                return ResourceManager.GetString("ExlporerTab.ContextMenu.OpenInNativeExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alt + Left Arrow.
        /// </summary>
        public static string ExplorerTab_ContextMenu_BackButtonGesture {
            get {
                return ResourceManager.GetString("ExplorerTab.ContextMenu.BackButtonGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string ExplorerTab_ContextMenu_BackButtonHeader {
            get {
                return ResourceManager.GetString("ExplorerTab.ContextMenu.BackButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alt + Right Arrow.
        /// </summary>
        public static string ExplorerTab_ContextMenu_ForwardButtonGesture {
            get {
                return ResourceManager.GetString("ExplorerTab.ContextMenu.ForwardButtonGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forward.
        /// </summary>
        public static string ExplorerTab_ContextMenu_ForwardButtonHeader {
            get {
                return ResourceManager.GetString("ExplorerTab.ContextMenu.ForwardButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        public static string ExplorerTab_ContextMenu_UpdateButtonHeader {
            get {
                return ResourceManager.GetString("ExplorerTab.ContextMenu.UpdateButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View.
        /// </summary>
        public static string ExplorerTab_ContextMenu_View {
            get {
                return ResourceManager.GetString("ExplorerTab.ContextMenu.View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drives.
        /// </summary>
        public static string MyComputer_DrivesHeader {
            get {
                return ResourceManager.GetString("MyComputer.DrivesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folders.
        /// </summary>
        public static string MyComputer_FolderHeader {
            get {
                return ResourceManager.GetString("MyComputer.FolderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string NotifyIcon_ContextMenu_ExitHeader {
            get {
                return ResourceManager.GetString("NotifyIcon.ContextMenu.ExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Window.
        /// </summary>
        public static string NotifyIcon_ContextMenu_ShowWindowHeader {
            get {
                return ResourceManager.GetString("NotifyIcon.ContextMenu.ShowWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Double-click for window, right-click for menu.
        /// </summary>
        public static string NotifyIcon_ToolTipText {
            get {
                return ResourceManager.GetString("NotifyIcon.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No access.
        /// </summary>
        public static string PageFactory_NotAccessCaption {
            get {
                return ResourceManager.GetString("PageFactory,NotAccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You do not have access to the folder.
        /// </summary>
        public static string PageFactory_NotAccessText {
            get {
                return ResourceManager.GetString("PageFactory,NotAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to &quot;{0}&quot;.
        /// </summary>
        public static string SearchHandler_RouteText {
            get {
                return ResourceManager.GetString("SearchHandler.RouteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search &quot;{0}&quot; in all folders.
        /// </summary>
        public static string SearchHandler_SearchAllDrivesText {
            get {
                return ResourceManager.GetString("SearchHandler.SearchAllDrivesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search &quot;{0}&quot; in the &quot;{1}&quot;.
        /// </summary>
        public static string SearchHandler_SearchDirectoryText {
            get {
                return ResourceManager.GetString("SearchHandler.SearchDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search &quot;{0}&quot; in the &quot;{1}&quot;.
        /// </summary>
        public static string SearchHandler_SearchDriveText {
            get {
                return ResourceManager.GetString("SearchHandler.SearchDriveText", resourceCulture);
            }
        }
    }
}
