//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFiler.Base.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XFiler.Base.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add to bookmarks.
        /// </summary>
        public static string ContextMenu_AddToBookmarks {
            get {
                return ResourceManager.GetString("ContextMenu.AddToBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        public static string ContextMenu_Copy {
            get {
                return ResourceManager.GetString("ContextMenu.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cut.
        /// </summary>
        public static string ContextMenu_Cut {
            get {
                return ResourceManager.GetString("ContextMenu.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string ContextMenu_Delete {
            get {
                return ResourceManager.GetString("ContextMenu.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string ContextMenu_Open {
            get {
                return ResourceManager.GetString("ContextMenu.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open in Windows Explorer.
        /// </summary>
        public static string ContextMenu_OpenInNativeExplorer {
            get {
                return ResourceManager.GetString("ContextMenu.OpenInNativeExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open in new tab.
        /// </summary>
        public static string ContextMenu_OpenInNewTab {
            get {
                return ResourceManager.GetString("ContextMenu.OpenInNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open in new window.
        /// </summary>
        public static string ContextMenu_OpenInNewWindow {
            get {
                return ResourceManager.GetString("ContextMenu.OpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste.
        /// </summary>
        public static string ContextMenu_Paste {
            get {
                return ResourceManager.GetString("ContextMenu.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename.
        /// </summary>
        public static string ContextMenu_Rename {
            get {
                return ResourceManager.GetString("ContextMenu.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Presenters_Content {
            get {
                return ResourceManager.GetString("Presenters.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Large icons.
        /// </summary>
        public static string Presenters_LargeIcons {
            get {
                return ResourceManager.GetString("Presenters.LargeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regular icons.
        /// </summary>
        public static string Presenters_RegularIcons {
            get {
                return ResourceManager.GetString("Presenters.RegularIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Small icons.
        /// </summary>
        public static string Presenters_SmallIcons {
            get {
                return ResourceManager.GetString("Presenters.SmallIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table.
        /// </summary>
        public static string Presenters_Table {
            get {
                return ResourceManager.GetString("Presenters.Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of change.
        /// </summary>
        public static string Presenters_Table_DateOfChangeRow {
            get {
                return ResourceManager.GetString("Presenters.Table.DateOfChangeRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Presenters_Table_NameRow {
            get {
                return ResourceManager.GetString("Presenters.Table.NameRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size.
        /// </summary>
        public static string Presenters_Table_SizeRow {
            get {
                return ResourceManager.GetString("Presenters.Table.SizeRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string Presenters_Table_TypeRow {
            get {
                return ResourceManager.GetString("Presenters.Table.TypeRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tiles.
        /// </summary>
        public static string Presenters_Tiles {
            get {
                return ResourceManager.GetString("Presenters.Tiles", resourceCulture);
            }
        }
    }
}
